import { defineStore } from 'pinia'

export const useTripsStore = defineStore('trips', {
  state: () => ({
    trips: [
      {
        id: '1',
        title: 'Portugāles piekraste',
        dates: '2025. gada marts',
        description: 'Dabas takas, okeāns un brīvības sajūta gar Rota Vicentina maršrutu.',
        image: 'https://picsum.photos/seed/portugal/600/400',
      },
      {
        id: '2',
        title: 'Alpu pārgājiens',
        dates: '2025. gada jūlijs',
        description: 'Augstkalnu piedzīvojums Šveices un Itālijas Alpos ar ainavām kā no pastkartes.',
        image: 'https://picsum.photos/seed/alps/600/400',
      },
      {
        id: '3',
        title: 'Balkānu treks',
        dates: '2025. gada septembris',
        description: 'Mazāk zināmas takas un kalni Albānijā un Melnkalnē.',
        image: 'https://picsum.photos/seed/balkans/600/400',
      },
      {
        id: '4',
        title: 'Islande – uguns un ledus zeme',
        dates: '2025. gada jūnijs',
        description: 'Aizraujošs pārgājiens pa Landmannalaugar maršrutu.',
        image: 'https://picsum.photos/seed/iceland/600/400',
      },
      {
        id: '5',
        title: 'Norvēģijas fjordi',
        dates: '2025. gada augusts',
        description: 'Kalnu pārgājieni ar skatiem uz dziļajiem fjordiem.',
        image: 'https://picsum.photos/seed/norway/600/400',
      },
      {
        id: '6',
        title: 'Slovākijas Tatri',
        dates: '2025. gada oktobris',
        description: 'Īsāki, bet ainaviski bagāti kalnu pārgājieni tuvāk mājām.',
        image: 'https://picsum.photos/seed/tatra/600/400',
      },
      {
        id: '7',
        title: 'Grieķijas Meteora un Olimps',
        dates: '2025. gada maijs',
        description: 'Pārgājieni starp klosteriem un sengrieķu dievu kalnu.',
        image: 'https://picsum.photos/seed/greece/600/400',
      },
      {
        id: '8',
        title: 'Pireneji – Spānija un Francija',
        dates: '2025. gada jūlijs',
        description: 'Augstie Pireneju kalni, klusums un daba.',
        image: 'https://picsum.photos/seed/pyrenees/600/400',
      },
      {
        id: '9',
        title: 'Skotijas Highlands',
        dates: '2025. gada jūnijs',
        description: 'Miglas kalni, ezeri un mistiska atmosfēra.',
        image: 'https://picsum.photos/seed/scotland/600/400',
      },
      {
        id: '10',
        title: 'Itālijas Dolomīti',
        dates: '2025. gada augusts',
        description: 'Ainaviskas virsotnes un tehniski viegli maršruti.',
        image: 'https://picsum.photos/seed/dolomites/600/400',
      },
      {
        id: '11',
        title: 'Madeiras kalnu takas',
        dates: '2025. gada novembris',
        description: 'Tropiska sala ar Levadas un kalnu pārgājieniem.',
        image: 'https://picsum.photos/seed/madeira/600/400',
      },
      {
        id: '12',
        title: 'Rumānijas Karpati',
        dates: '2025. gada oktobris',
        description: 'Savvaļas daba, lāči un autentiska pieredze.',
        image: 'https://picsum.photos/seed/carpathians/600/400',
      },
      {
        id: '13',
        title: 'Igaunijas nacionālie parki',
        dates: '2025. gada aprīlis',
        description: 'Vieglas pastaigas purvos un piekrastes takās.',
        image: 'https://picsum.photos/seed/estonia/600/400',
      },
      {
        id: '14',
        title: 'Austrijas Alpu ciemati',
        dates: '2025. gada septembris',
        description: 'Kalnu ciematu šarms un panorāmas skati.',
        image: 'https://picsum.photos/seed/austria/600/400',
      },
      {
        id: '15',
        title: 'Horvātijas piekrastes pārgājiens',
        dates: '2025. gada jūlijs',
        description: 'Dienvidu saule, jūra un dabas takas.',
        image: 'https://picsum.photos/seed/croatia/600/400',
      },
      {
        id: '16',
        title: 'Ceļojums uz Korsiku',
        dates: '2025. gada maijs',
        description: 'Leģendārais GR20 maršruts un Vidusjūras skati.',
        image: 'https://picsum.photos/seed/corsica/600/400',
      },
      {
        id: '17',
        title: 'Velsas kalnu grēdas',
        dates: '2025. gada jūnijs',
        description: 'Snowdonia nacionālais parks un senu ciltu mantojums.',
        image: 'https://picsum.photos/seed/wales/600/400',
      },
      {
        id: '18',
        title: 'Polijas Bieszczady',
        dates: '2025. gada septembris',
        description: 'Tukšas kalnu pļavas, klusums un mierīga daba.',
        image: 'https://picsum.photos/seed/poland/600/400',
      },
      {
        id: '19',
        title: 'Turcijas Līcijas taka',
        dates: '2025. gada oktobris',
        description: 'Vēsturiski ciemati un Vidusjūras panorāmas.',
        image: 'https://picsum.photos/seed/lycian/600/400',
      },
      {
        id: '20',
        title: 'Ziemeļnorvēģijas Lofotu salas',
        dates: '2025. gada augusts',
        description: 'Dramatiski kalni, fjordi un jūra vienuviet.',
        image: 'https://picsum.photos/seed/lofoten/600/400',
      },
    ],
  }),
})
